[server]
headless = true
address = "0.0.0.0"
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#FF9933"
backgroundColor = "#FAFBFF"
secondaryBackgroundColor = "#F0F2FF"
textColor = "#2c3e50"
